In [4]:
import numpy as np
import statistics as st
baked_food = [200,300,150,130,200,280,170,188]

a = np.array(baked_food)
print(np.mean(a))
print(np.median(a))
print(st.mode(a))
print(np.std(a))
print(np.var(a))
print(np.sort(a))

202.25
194.0
200
55.68157235567257
3100.4375
[130 150 170 188 200 200 280 300]


In [7]:
# -1 represents inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship

tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

print(np.corrcoef(tobacco_consumption,deaths))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [8]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]

print(np.corrcoef(price,sales))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
