In [3]:
import numpy as np

a = np.array([[20,40],[40,80]])
print(np.append(a,[10,40]))

[20 40 40 80 10 40]


In [6]:
print(np.insert(a,0,10))
print(np.insert(a,1,[40,30], axis=1))

[10 20 40 40 80]
[[20 40 40]
 [40 30 80]]


In [12]:
a = np.array([[20,40],[60,80]])
print(a)
np.delete(a,1)

[[20 40]
 [60 80]]


array([20, 60, 80])

In [13]:
print(a)

[[20 40]
 [60 80]]
