In [3]:
import numpy as np
a = np.array([20,40,60,80])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))


200
20
80
4
50.0
[ 20  60 120 200]
[     20     800   48000 3840000]


In [9]:
a = [100,150,199,220,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price, quantity)
print(np.sum(price))
print(np.sum(quantity))

print(np.cumprod([price, quantity], axis=0))


[100 150 199 220 250 130] [10 50 30 40 30 10]
1049
170
[[ 100  150  199  220  250  130]
 [1000 7500 5970 8800 7500 1300]]
