In [1]:
import numpy as np
a = [30,40,50]
b = [10,20,30]
print(a+b)


[30, 40, 50, 10, 20, 30]


In [8]:
arr1=np.array([[30,40],[20,10]])
arr2=np.array([[10,20],[50,40]])
print(np.concatenate([arr1,arr2]))
print("\n")
print(np.concatenate([arr1,arr2], axis=1))
print("\n")


[[30 40]
 [20 10]
 [10 20]
 [50 40]]


[[30 40 10 20]
 [20 10 50 40]]


[[30 40 10 20]
 [20 10 50 40]]


In [11]:
print(np.hstack([arr1,arr2]))
print("\n")
print(np.vstack([arr1,arr2]))

[[30 40 10 20]
 [20 10 50 40]]


[[30 40]
 [20 10]
 [10 20]
 [50 40]]


In [14]:
a = np.array([20,40,50,55,60,10,200])
b = np.array_split(a,4)
print(b)

[array([20, 40]), array([50, 55]), array([60, 10]), array([200])]
