In [2]:
import numpy as np

In [10]:
a = np.array([20 ,30, 40])
b = np.array([200 ,300, 400])
c = np.array([[20,30,40],[60,70,50]])

In [11]:
print(a)
print(b)
print(c)
print(a*b)

[20 30 40]
[200 300 400]
[[20 30 40]
 [60 70 50]]
[ 4000  9000 16000]


In [5]:
l1=[[20,30],[40,50]]
print(l1)

[[20, 30], [40, 50]]
