In [1]:
import numpy as np

In [4]:
ar = np.array([[7,8,4],[2,1,9]])

In [5]:
 print(np.sort(ar))

[[4 7 8]
 [1 2 9]]


In [9]:
ar = np.array([7,8,4,2,1,9])
s = np.where(ar % 2 == 0)
print(s)

(array([1, 2, 3]),)


In [20]:
arr = np.array([10,20,30,40,50,60,70,80,90])
ss = np.searchsorted(arr, 5)
print(ss+1)

1


In [29]:
arr = np.array([10,20,30,40])
fa = [True, False, True, False]
x = arr[fa]
print(x)

[10 30]


In [31]:
arr = np.array([10,20,30,40])
fa = arr>35
x = arr[fa]
print(x)

[40]


In [33]:
arr = np.array([2,3,4,5])
fa = arr%2==1
x = arr[fa]
print(x)

[3 5]
